base_url: http://basetta.pupazzo.org
cdn_url: http://basetta.pupazzo.org
content_width: 640
copyright: { starting_year: 2012, owner: Patrick Martini }
description: 'Rants and Raves'
google_analytics_account: UA-3020776-9
hidden_files: true
jquery_version: 1.9.0
kramdown: { entity_output: symbolic }
remove_obsolete: true
search_sites: basetta.pupazzo.org
title: Basetta's Website
visible_posts: 5
